const fs = require('fs');
const path = require('path');

const HISTORY_FILE = path.join(__dirname, 'history.json');

/**
 * Ensures the history file exists.
 */
function initHistory() {
    if (!fs.existsSync(HISTORY_FILE)) {
        fs.writeFileSync(HISTORY_FILE, JSON.stringify([], null, 2));
    }
}

/**
 * Saves a new chat interaction.
 * @param {string} jid The user's WhatsApp number ID
 * @param {string} userMessage The text/query sent by the user
 * @param {string} aiResponse The response generated by the AI
 * @param {boolean} hasImage Whether the request contained an image
 * @param {string} mediaUrl URL to the saved media file locally
 */
function logInteraction(jid, userMessage, aiResponse, hasImage = false, mediaUrl = null) {
    try {
        initHistory();
        const data = fs.readFileSync(HISTORY_FILE, 'utf8');
        const history = JSON.parse(data);

        // Limit history to last 500 messages to prevent huge file sizes
        if (history.length > 500) {
            history.shift(); 
        }

        const newEntry = {
            id: Date.now(),
            timestamp: new Date().toISOString(),
            user: jid,
            query: userMessage || (hasImage ? "[Sent an Image]" : "[Unknown]"),
            response: aiResponse,
            hasImage: hasImage,
            mediaUrl: mediaUrl
        };

        history.push(newEntry);
        fs.writeFileSync(HISTORY_FILE, JSON.stringify(history, null, 2));
    } catch (e) {
        console.error("Failed to log interaction:", e);
    }
}

/**
 * Gets the chat history, sorted newest first
 */
function getHistory() {
    try {
        initHistory();
        const data = fs.readFileSync(HISTORY_FILE, 'utf8');
        const history = JSON.parse(data);
        return history.reverse(); // Newest first
    } catch (e) {
        console.error("Failed to load history:", e);
        return [];
    }
}

/**
 * Gets the chat history for a specific user to maintain context
 */
function getUserHistory(jid, limit = 5) {
    try {
        initHistory();
        const data = fs.readFileSync(HISTORY_FILE, 'utf8');
        const history = JSON.parse(data);
        const user = jid.split('@')[0];
        
        // Return oldest first for the prompt context, max 'limit' entries
        return history.filter(h => h.user === user).slice(-limit);
    } catch (e) {
        console.error("Failed to load user history:", e);
        return [];
    }
}

module.exports = {
    logInteraction,
    getHistory,
    getUserHistory
};
